[package]
name = "stimmgabel"
version = "0.1.0"
edition = "2021"
description = "polyproto reference server and client implementation used for verifying other implementations of the protocol."
license = "MPL-2.0"
repository = "https://github.com/polyphony-chat/stimmgabel"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.0", features = ["derive"] }
tokio = { version = "1.36.0", features = ["rt", "macros", "net"] }
colored = "2.1.0"
lazy_static = "1.4.0"
axum = { version = "0.7.4", optional = true }
reqwest = { version = "0.11.24", optional = true }

[features]
default = ["client", "server"]
client = ["dep:reqwest"]
server = ["dep:axum"]
