[package]
name = "stimmgabel"
version = "0.1.0"
edition = "2021"
description = "polyproto reference server and client implementation used for verifying other implementations of the protocol."
license = "MIT"
repository = "https://github.com/polyphony-chat/stimmgabel"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["client", "server"]

[dependencies]
server = { path = "./server" }
client = { path = "./client" }
clap = { version = "4.5.0", features = ["derive"] }
tokio = { version = "1.36.0", features = ["rt", "macros", "net"] }
colored = "2.1.0"
